# Generated by Django 4.0.4 on 2022-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('game_type', models.IntegerField(default={('Baseball', 'Baseball'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Football', 'Football')})),
                ('time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('img', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
