# Generated by Django 4.0.4 on 2022-04-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball')], max_length=50),
        ),
    ]
