# Generated by Django 4.0.4 on 2022-04-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
