# Generated by Django 4.0.4 on 2022-04-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_alter_game_game_type_alter_game_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Soccer', 'Soccer')], max_length=50),
        ),
    ]
