# Generated by Django 4.0.4 on 2022-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_game_user_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Football', 'Football'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball')], max_length=50),
        ),
    ]
