# Generated by Django 4.0.4 on 2022-04-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Football', 'Football')], max_length=50),
        ),
    ]
