# Generated by Django 4.0.4 on 2022-04-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_game_game_type_alter_game_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Soccer', 'Soccer')], max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='member',
            field=models.ManyToManyField(to='main_app.member'),
        ),
    ]
