# Generated by Django 4.0.4 on 2022-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_member_remove_game_user_alter_game_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Football', 'Football'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Soccer', 'Soccer')], max_length=50),
        ),
    ]
