# Generated by Django 4.0.4 on 2022-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'), ('Soccer', 'Soccer')], max_length=50),
        ),
    ]
