# Generated by Django 4.0.4 on 2022-04-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_game_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Volleyball', 'Volleyball'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Football', 'Football'), ('Basketball', 'Basketball')], max_length=50),
        ),
    ]
