# Generated by Django 4.0.4 on 2022-04-20 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_group_remove_game_member_game_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Soccer', 'Soccer')], max_length=50),
        ),
    ]
