# Generated by Django 4.0.3 on 2022-04-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_game_group_group_members_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ManyToManyField(null=True, to='main_app.group'),
        ),
    ]
