# Generated by Django 4.0.3 on 2022-04-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_game_game_type_remove_game_group_game_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group'),
        ),
    ]
