# Generated by Django 4.0.3 on 2022-04-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Basketball', 'Basketball'), ('Football', 'Football'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ManyToManyField(null=True, to='main_app.group'),
        ),
    ]
