# Generated by Django 4.0.3 on 2022-04-20 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0021_alter_game_game_type_remove_game_group_game_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Baseball', 'Baseball'), ('Soccer', 'Soccer'), ('Football', 'Football')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='game',
            name='group',
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
