# Generated by Django 4.0.4 on 2022-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_alter_game_game_type_alter_game_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Volleyball', 'Volleyball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Basketball', 'Basketball')], max_length=50),
        ),
    ]
