# Generated by Django 4.0.4 on 2022-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Football', 'Football'), ('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball')], max_length=50),
        ),
    ]
