# Generated by Django 4.0.3 on 2022-04-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_alter_game_game_type_alter_game_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Football', 'Football'), ('Soccer', 'Soccer'), ('Volleyball', 'Volleyball'), ('Basketball', 'Basketball'), ('Baseball', 'Baseball')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.group'),
        ),
    ]
